#
# Path to the root of the development system.
#
BASE_PATH := ../..

#
# Define the target files.
#
TARGET_BIN := c8_check

#
# Define the source files.
#
SRCS := \
    c8_check.cpp \
    integer_check.cpp \
    natural_check.cpp \
    rational_check.cpp

#
# Libraries.
#
LIBS := \
    -lc8

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/test.mk

