#
# Path to the root of the development system.
#
BASE_PATH := ..

#
# Define our subdirectories.
#
SUBDIRS := \
    integer_check \
    integer_dep \
	natural_check \
	natural_dep \
	rational_check \
	rational_dep \
	real10_check \
	real10_dep \
	real2_check \
	real2_dep

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/dir.mk

