#
# Path to the root of the development system.
#
BASE_PATH := ..

#
# Define our subdirectories.
#
SUBDIRS := \
	c8_check \
	natural_dep \
	integer_dep \
	rational_dep \
	natural_perf \
	rational_perf

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/dir.mk

