#
# Path to the root of the development system.
#
BASE_PATH := ../..

#
# Library depedencies.
#
DEP_LIBS :=

#
# Define the target files.
#
TARGET_LIB := libnatural.a

#
# Define the source files for various apps.
#
SRCS := \
	natural.cpp

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/lib.mk

