#
# Path to the root of the development system.
#
BASE_PATH := ..

#
# Define the source files for various apps.
#
SRCS := \
	c8.md \
	c8_integer.md \
	c8_integer_divide_modulus.md \
	c8_integer_integer.md \
	c8_integer_is_negative.md \
	c8_integer_is_zero.md \
	c8_integer_operator_di.md \
	c8_integer_operator_dieq.md \
	c8_integer_operator_eq.md \
	c8_integer_operator_eqeq.md \
	c8_integer_operator_exeq.md \
	c8_integer_operator_gt.md \
	c8_integer_operator_gteq.md \
	c8_integer_operator_gtgt.md \
	c8_integer_operator_gtgteq.md \
	c8_integer_operator_lt.md \
	c8_integer_operator_lteq.md \
	c8_integer_operator_ltlt.md \
	c8_integer_operator_ltlteq.md \
	c8_integer_operator_mi.md \
	c8_integer_operator_mieq.md \
	c8_integer_operator_mo.md \
	c8_integer_operator_moeq.md \
	c8_integer_operator_mu.md \
	c8_integer_operator_mueq.md \
	c8_integer_operator_pl.md \
	c8_integer_operator_pleq.md \
	c8_integer_operator_unary_mi.md \
	c8_natural.md \
	c8_natural_divide_modulus.md \
	c8_natural_is_zero.md \
	c8_natural_natural.md \
	c8_natural_operator_di.md \
	c8_natural_operator_dieq.md \
	c8_natural_operator_eq.md \
	c8_natural_operator_eqeq.md \
	c8_natural_operator_exeq.md \
	c8_natural_operator_gt.md \
	c8_natural_operator_gteq.md \
	c8_natural_operator_gtgt.md \
	c8_natural_operator_gtgteq.md \
	c8_natural_operator_lt.md \
	c8_natural_operator_lteq.md \
	c8_natural_operator_ltlt.md \
	c8_natural_operator_ltlteq.md \
	c8_natural_operator_mi.md \
	c8_natural_operator_mieq.md \
	c8_natural_operator_mo.md \
	c8_natural_operator_moeq.md \
	c8_natural_operator_mu.md \
	c8_natural_operator_mueq.md \
	c8_natural_operator_pl.md \
	c8_natural_operator_pleq.md \
	c8_natural_size_bits.md \
	c8_rational.md \
	c8_rational_is_zero.md \
	c8_rational_operator_di.md \
	c8_rational_operator_dieq.md \
	c8_rational_operator_eq.md \
	c8_rational_operator_eqeq.md \
	c8_rational_operator_exeq.md \
	c8_rational_operator_gt.md \
	c8_rational_operator_gteq.md \
	c8_rational_operator_lt.md \
	c8_rational_operator_lteq.md \
	c8_rational_operator_mi.md \
	c8_rational_operator_mieq.md \
	c8_rational_operator_mu.md \
	c8_rational_operator_mueq.md \
	c8_rational_operator_pl.md \
	c8_rational_operator_pleq.md \
	c8_rational_operator_unary_mi.md \
	c8_rational_rational.md \

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/doc.mk

