#
# Path to the root of the development system.
#
BASE_PATH := ..

#
# Define the source files for various apps.
#
SRCS := \
	c8.md \
	c8_integer.md \
	c8_integer_operator_assign.md \
	c8_integer_operator_arithmetic.md \
	c8_integer_operator_bitwise.md \
	c8_integer_operator_compare.md \
	c8_natural.md \
	c8_natural_natural.md \
	c8_natural_operator_assign.md \
	c8_natural_operator_arithmetic.md \
	c8_natural_operator_bitwise.md \
	c8_natural_operator_compare.md \
	c8_natural_size_bits.md \
	c8_rational.md \
	c8_rational_operator_assign.md \
	c8_rational_operator_arithmetic.md \
	c8_rational_operator_compare.md \

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/doc.mk

