#
# Path to the root of the development system.
#
BASE_PATH := ../..

#
# Define the target files.
#
TARGET_BIN := integer_check

#
# Define the source files.
#
SRCS := integer_check.cpp

#
# Libraries.
#
LIBS := \
    -lc8

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/test.mk

