#
# Path to the root of the development system.
#
BASE_PATH := ../..

#
# Define the target files.
#
TARGET_BIN := scale10_dep

#
# Define the source files.
#
SRCS := scale10_dep.cpp

#
# Libraries.
#
LIBS := \
    -lc8

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/test.mk

