#
# Path to the root of the development system.
#
BASE_PATH := ../..

#
# Define the target files.
#
TARGET_BIN := natural_dep

#
# Define the source files.
#
SRCS := natural_dep.cpp

#
# Libraries.
#
LIBS := \
    -lnatural

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/test.mk

