#
# Path to the root of the development system.
#
BASE_PATH := ..

#
# Library depedencies.
#
DEP_LIBS :=

#
# Define the target files.
#
TARGET_LIB := libc8.a

#
# Define the source files for various apps.
#
SRCS := \
	integer/integer.cpp \
    natural/natural.cpp \
    rational/rational.cpp \
    real10/real10.cpp \
    real2/real2.cpp

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/lib.mk

