#
# Path to the root of the development system.
#
BASE_PATH := ..

#
# Define our subdirectories.
#
SUBDIRS := \
    natural

#
# Ensure that we reflect the dependencies on the various libraries!
#

#
# Actual heavy lifting for the make.
#
include $(BASE_PATH)/build/dir.mk

